repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.4
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ["--fix"] # Optional: auto-fix issues
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        args: []
        additional_dependencies: &mypy_deps
          - types-PyYAML
          - types-atheris
          - types-tqdm
          - tomli >= 0.2.6, < 2.0.0
          - click >= 8.2.0
          # Click is intentionally out-of-sync with pyproject.toml
          # v8.2 has breaking changes. We work around them at runtime, but we need the newer stubs.
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytokens >= 0.1.10
          - pytest
          - hypothesis
          - aiohttp >= 3.7.4
          - types-commonmark
          - urllib3
          - hypothesmith
          - selenium >= 4.35.0
          - webdriver-manager
          - sqlalchemy
          - python-docx
          - python-dotenv
          - fake-useragent
          - python-json-logger
          - undetected-chromedriver
          - hydra-core
          - omegaconf
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        exclude: ^tests/|^test_.*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
