host: smtp.gmail.com
port: 587
username: ${oc.env:SMTP_USER, null}
password: ${oc.env:SMTP_PASS, null}
from_addr: mohammadmuntasir96@gmail.com
to_addr:
  - tanay@idlc.com
cc_addr:
  - muntasirm@idlc.com
  - zareen@idlc.com
  - mtashnim@idlc.com
  - mdfahad@idlc.com
