level: INFO
handlers:
  - console
  - file
fmt: "%(asctime)s %(processName)s %(name)s %(levelname)s %(message)s"
file:
  folder_location: ./logs/
  name: scraper.log
  when: midnight
  backup_count: 7
queue:
  # maxsize for multiprocessing.Queue (-1 = infinite)
  maxsize: -1
