from .crud import (
    bulk_delete_by_source,
    count_articles,
    create_article,
    delete_article_by_id,
    delete_article_by_url,
    ensure_tables,
    get_article_by_date,
    get_article_by_id,
    get_article_by_url,
    get_articles_by_start_and_end_date,
    insert_articles_batch,
    list_articles,
    save_scraped_items,
    update_article_by_id,
    update_article_by_url,
)
from .models import Base, NewsArticle
from .session import get_engine, get_session

__all__ = [
    "bulk_delete_by_source",
    "count_articles",
    "create_article",
    "delete_article_by_id",
    "delete_article_by_url",
    "ensure_tables",
    "get_article_by_id",
    "get_article_by_url",
    "get_article_by_date",
    "get_articles_by_start_and_end_date",
    "insert_articles_batch",
    "list_articles",
    "save_scraped_items",
    "update_article_by_id",
    "update_article_by_url",
    "Base",
    "NewsArticle",
    "get_engine",
    "get_session",
]
