defaults:
  - _self_
  - runtime: prod
  - webdriver: chrome
  - celery: celery
  - sites:
      - bonik_barta
      - daily_star
      - janakantha
      - prothom_alo
  - override hydra/job_logging: logger

max_retries: 3
output_location:
  raw: ${hydra:runtime.output_dir}/project_outputs/raw
  processed: ${hydra:runtime.output_dir}/project_outputs/processed
resource:
  news_digest_template: ./resources/newsdigest_template.docx
  vault: ./resources/fail_safe_vault.json

webdriver:
  options:
    headless: true
    no-sandbox: true
    disable-dev-shm-usage: true
    disable-blink-features: AutomationControlled
    enable-gpu-rasterization: true
