driver: mysql
host: mysql-1f588591-mohammadmuntasir96-a8a9.g.aivencloud.com
port: 24224
user: ${oc.env:DB_USER, ""}
password: ${oc.env:DB_PASS, ""} # enforce via env / secret manager
database_name: defaultdb
url: ${oc.env:DB_URL, ""}
pool:
  size: 10
  max_overflow: 20
  recycle_time: 3600
  pre_ping: true
ssl:
  mode: REQUIRED
  ca_path: ${oc.env:DB_SSL_CA_PATH, ""}
