daily_star:
  name: The Daily Star Bangla
  base_url: https://bangla.thedailystar.net
  url_list:
    Bangladesh: https://bangla.thedailystar.net/news/bangladesh
    International: https://bangla.thedailystar.net/international
    Business: https://bangla.thedailystar.net/business
  selectors:
    news_link_list:
    datetime:
    title:
    body:
    cloudflare: null
  rate_limiter: 0
